keycloak:
  enabled: true
#  realm: CNR
  realm: cnr
  auth-server-url: http://dockerwebtest02.si.cnr.it:8110/auth
  #  auth-server-url: https://sso.cnr.it/auth
  ssl-required: NONE
  enable-basic-auth: true
  resource: missioni
  public-client: false
  use-resource-role-mappings: true
  credentials:
    secret:


sso:
  cnr:
    user: is_cnr_user
    matricola: matricola_cnr
    livello: livello
    contesto: missioni-app
    username_cnr: username_cnr
    userinfo_endpoint: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/userinfo

spring:
  main:
    # TODO - Workaround for circular dependency of KeycloakWebSecurityConfigurerAdapter https://github.com/keycloak/keycloak/issues/8857
    allow-circular-references: true
  session:
    hazelcast:
  proxy:
    SIGLA:
      client_credentials: true