spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://as4dock.si.cnr.it:54321/missioni
        name: missioni
        username: missioni
        password: missionipw
#        url: jdbc:postgresql://jspringdb.src.cnr.it:5432/missioni
#        name: missioni
#        username: missioni
#        password: missioniPW

    jpa:
        database-platform: it.cnr.si.domain.util.FixedPostgreSQL82Dialect
        database: POSTGRESQL

    proxy:
        SIGLA:
            url: http://sigla-main.test.si.cnr.it/SIGLA/
        #    url: http://sigla-main-multi-impegni.test.si.cnr.it/SIGLA/
        #    url: http://localhost:8080/SIGLA/
        #    url: http://contab.cnr.it:90/SIGLA/
            username: MISSIONI
            password: M15510N1
            context:
                cd_unita_organizzativa: "999.000"
                cd_cds: "999"
                cd_cdr: "999.000.000"
        SIPER:
    #            url: https://testsiper.si.cnr.it/siper/
            url: https://siper.cnr.it/siper/
            username: app.selezioni
            password: pentagono
        STORAGE:
    #            url: https://testsiper.si.cnr.it/siper/
            url: http://as1dock.si.cnr.it:8080/alfresco/
            username: missioni.missioni
            password: missioni
            urlForPerson: service/cnr/person/person/
        OIL:
            username: missioni1
            password: missioni.1
            url: http://oil.test.si.cnr.it/rest/
            newProblem: pest
            instance: /HDSiper
        FLOWS:
            urlOrdineMissione: service/api/workflow/activiti$flussoMissioniOrdine/formprocessor
            urlAnnullamentoOrdineMissione: service/api/workflow/activiti$flussoMissioniRevoca/formprocessor
            urlRimborsoMissione: service/api/workflow/activiti$flussoMissioniRimborso/formprocessor
    ldap:
        userSearchBase: o=cnr, c=it
        userSearchFilter: uid={0}
        url: ldap://virtest1.si.cnr.it:389
        managerDn: cn=mastercnrapp2,ou=account,o=cnr,c=it
        managerPassword: pippa

    mail:
        host: smtp.cnr.it
        protocol: smtp
        port: 25
        from: missioni@cnr.it
        tls: false
        auth: false
        send.error.to: gianfranco.gasparro@cnr.it

    rabbitmq:
#        host: rabbitmq.cedrc.cnr.it
        host: missioni-rabbit.test.si.cnr.it
        username: cnr
        password: bubbazza
        virtualHost: missioni
        exchange: missioni
        routing-key: 
        consumer:
            name: loopback

    print:
        endpoint: http://sigla-print.test.si.cnr.it/api/v1/get/print

ajp:
    port: 8009
    timeout: 120000

audit: false

siper:
  url: ${spring.proxy.SIPER.url}json/userinfo/
  urldett: ${spring.proxy.SIPER.url}json/userinfodett/
  username: ${spring.proxy.SIPER.username}
  password: ${spring.proxy.SIPER.password}

storage:
    maxItemsPerPage: 10
    folder_path: /Comunicazioni al CNR/Missioni
    folder_path_config: /Config
    folder_path_manual: /Config/Manuali

user.admin.username: ${spring.proxy.STORAGE.username}
user.admin.password: ${spring.proxy.STORAGE.password}
org.apache.chemistry.opencmis.binding.atompub.url: ${spring.proxy.STORAGE.url}api/-default-/public/cmis/versions/1.1/atom
repository.base.url: ${spring.proxy.STORAGE.url}
org.apache.chemistry.opencmis.binding.browser.url: ${spring.proxy.STORAGE.url}api/-default-/public/cmis/versions/1.1/browser
org.apache.chemistry.opencmis.binding.spi.type: atompub
org.apache.chemistry.opencmis.binding.connecttimeout: 50000
org.apache.chemistry.opencmis.binding.readtimeout: 3000000
org.apache.chemistry.opencmis.binding.httpinvoker.classname: org.apache.chemistry.opencmis.client.bindings.spi.http.DefaultHttpInvoker

cache:
    init_cache: true

logging.config: classpath:logback-local.xml

cron:
    comunicaDati:
        name: comunicaDati
        active: true
        cronExpression: "0 */1 * * * MON-SAT"

    evictCache:
        name: evictCache
        active: false
        cronExpression: "0 0 2 * * MON-SAT"

    loadCache:
        name: loadCache
        active: false
        cronExpression: "0 0 3 * * MON-SAT"

    verifyStep:
        name: verifyStep
        active: false
        cronExpression: "0 */1 * * * MON-SAT"

jhipster:
    mail:
        from: missioni@cnr.it

cache.hazelcast:
    name: sprint-missioni
    members: 127.0.0.1

server:
    port: 8081
