# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    profiles:
        active: prod
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    datasource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url: 
        databaseName: missioni
        serverName: localhost
        username: missioni
        password: 
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: it.cnr.si.config.hazelcast.HazelcastCacheRegionFactory
            hibernate.cache.use_minimal_puts: true
            hibernate.cache.hazelcast.use_lite_member: true
    mail:
        host: smtp.cnr.it
        port: 25
        username:
        password:
        tls: false
        auth: false
    proxy:
        SIGLA:
            url: http://test15.si.cnr.it:8180/SIGLA/
            username: MISSIONI
            password: M15510N1
            context:
                cd_unita_organizzativa: "999.000"
                cd_cds: "999"
                cd_cdr: "999.000.000"
        SIPER:
            url: https://siper.cnr.it/siper/
            username: app.selezioni
            password: pentagono
    ldap:
        userSearchBase: o=cnr, c=it
        userSearchFilter: uid={0}
        url: ldap://virtest1.si.cnr.it:389
        managerDn: cn=mastercnrapp2,ou=account,o=cnr,c=it
        managerPassword: pippa
    cmis:
        repository.base.url: http://as1dock.si.cnr.it:8080/alfresco/
        org.apache.chemistry.opencmis.binding.atompub.url: api/-default-/public/cmis/versions/1.1/atom
        org.apache.chemistry.opencmis.binding.spi.type: atompub
        org.apache.chemistry.opencmis.binding.connecttimeout: 50000
        org.apache.chemistry.opencmis.binding.readtimeout: 3000000
        org.apache.chemistry.opencmis.binding.httpinvoker.classname: org.apache.chemistry.opencmis.client.bindings.spi.http.DefaultHttpInvoker

        user.admin.username: app.missioni
        user.admin.password: bubbazza
        folder_path: /Missioni
        folder_path_config: /Config
    thymeleaf:
        cache: true
    print:
        baseDir: /it/cnr/missioni/print/

liquibase:
    contexts: prod

server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    http:
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 31
    cache: # Hibernate 2nd level cache, used by CacheConfiguration
        timeToLiveSeconds: 3600
        hazelcast:
            backupCount: 1
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: missioni@cnr.it
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: sprint

ajp:
    port: 8009
    timeout: 120000


siper:
  url: https://siper.cnr.it/siper/json/userinfo/
  username: app.selezioni
  password: pentagono

info:
    app:
        name: missioni
        version: @project.version@
