spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://as4dock.si.cnr.it:54321/missioni
        name: missioni
        username: missioni
        password: missionipw

    jpa:
        database-platform: it.cnr.si.domain.util.FixedPostgreSQL82Dialect
        database: POSTGRESQL

    proxy:
        SIGLA:
            url: http://sigla-main-rest-missioni.test.si.cnr.it/SIGLA/
        #    url: http://localhost:8080/SIGLA/
            username: MISSIONI
            password: M15510N1
            context:
                cd_unita_organizzativa: "999.000"
                cd_cds: "999"
                cd_cdr: "999.000.000"
        SIPER:
    #            url: https://testsiper.si.cnr.it/siper/
            url: https://siper.cnr.it/siper/
            username: app.selezioni
            password: pentagono
    ldap:
        userSearchBase: o=cnr, c=it
        userSearchFilter: uid={0}
        url: ldap://virtest1.si.cnr.it:389
        managerDn: cn=mastercnrapp2,ou=account,o=cnr,c=it
        managerPassword: pippa

    mail:
        host: smtp.cnr.it
        protocol: smtp
        port: 25
        from: missioni@cnr.it
        tls: false
        auth: false
        send.error.to: gianfranco.gasparro@cnr.it

    rabbitmq:
#        host: rabbitmq.cedrc.cnr.it
        host: missioni-rabbit.test.si.cnr.it
        username: cnr
        password: bubbazza
        virtualHost: missioni
        exchange: missioni
        routing-key: 
        consumer:
            name: loopback

ajp:
    port: 8009
    timeout: 120000

siper:
  url: ${spring.proxy.SIPER.url}json/userinfo/
  urldett: ${spring.proxy.SIPER.url}json/userinfodett/
  username: ${spring.proxy.SIPER.username}
  password: ${spring.proxy.SIPER.password}

cmis:
    alfresco: http://as1dock.si.cnr.it:8080/alfresco/
    url: ${cmis.alfresco}api/-default-/public/cmis/versions/1.1/atom
    username: app.missioni
    password: bubbazza
    maxItemsPerPage: 10
    folder_path: /Comunicazioni al CNR/Missioni
    folder_path_config: /Config
    folder_path_manual: /Config/Manuali

cache:
    init_cache: true

logging.config: classpath:logback-local.xml

cron:
    comunicaDati:
        name: comunicaDati
        active: false
        cronExpression: "0 */10 * * * MON-SAT"

    evictCache:
        name: evictCache
        active: false
        cronExpression: "0 0 2 * * MON-SAT"

    loadCache:
        name: loadCache
        active: false
        cronExpression: "0 0 3 * * MON-SAT"

jhipster:
    mail:
        from: missioni@cnr.it

cache.hazelcast:
    name: sprint-missioni
    members: 127.0.0.1

server:
    port: 8081
